# 熱像儀安裝位置與旋轉角度
# x-axis: 向右, y-axis: 向後, z-axis: 向上, yaw: 順時針為正
thermal_camera_pose:
  x: 0.0
  y: 0.125
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
# 熱像儀的視角
# unit is degree
thermal_camera_params:
  fov: 60
  width: 640  
  height: 480